baseURL = 'https://skyblue.team/'
languageCode = 'en-us'
title = 'Sky Blueteam'
theme = "mini"

[social]
github = "https://github.com/airbus-cert"

[params]
copyright = "&nbsp;"
customCSS = ["css/ribbon.css"]
customJS = ["js/ribbon.js"]